### ISSUE TITLE
Node 16 version deprecated

### ISSUE THREAD

**Issue by josesalvador** [3dwardCh3nG/delete-from-s3-action#141]
Hi, :-D
Github is complaining about the usage of Node 16 version.

![imagen](https://github.com/3dwardCh3nG/delete-from-s3-action/assets/2736452/473360df-2f67-43cf-a147-9d46967c8c8b)

Could you please update to a more recent version of Node?

I think it should be as easy as update this line of code to a more recent version:

![imagen](https://github.com/3dwardCh3nG/delete-from-s3-action/assets/2736452/693aacdf-a7e6-46ab-92be-3d4336ff1057)

Thank you in advance.

**Comment by 3dwardCh3nG** [comment]
Hi @josesalvador,

Thank you for creating this issue.

The update has been released just now. Please get the latest action if you need to use it.

Cheers,
Edward

**Comment by josesalvador** [comment]
Great!

Thanks for your time and your work! :-D
